parameters:
  - name: 'azureSubscription'
    default: 'devlevel3-dev-conn'
    type: string
  - name: 'appName'
    default: 'fa-tuapi-$(projName)-$(envName)-bra'
    type: string

jobs: 
- deployment: Deploy
  displayName: 'Deploy to dev'
  environment: $(envName)
  strategy:
   runOnce:
     deploy:
       steps:
       - task: AzureFunctionApp@1
         displayName: 'Deploy API'
         inputs:
           azureSubscription: ${{ parameters.azureSubscription }}
           appType: 'functionAppLinux'
           appName: ${{ parameters.appName }}
           package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
           runtimeStack: 'DOTNET|3.1'